### ISSUE TITLE
Automatic pickup of test result files for TeamCity

### ISSUE THREAD

**Issue by AwaNoodle** [lholman/OneBuild#35]
OneBuild could advertise the test result files in a similar way that it advertises its build number to Team City. This reduces the amount of steps needed in the build configuration. 

Adding ``##teamcity[importData type='nunit' path='$testResultFileName']`` after each test run is completed should do it.

**Comment by lholman** [comment]
@AwaNoodle I agree totally, however I'm actually trying to pull CI specifics out of OneBuild with #10 so you'd add OneBuild, then OneBuild.Ci.TeamCity for example for the implementations, needs some though about contracts/interfaces though, if you;re interested?

**Comment by lholman** [comment]
Closing this as we'll deal with all TeamCity specifics when looking at #10
