### ISSUE TITLE
Unit tests for New-NugetPackages are not using the mock for Get-AllNuSpecFiles

### ISSUE THREAD

**Issue by AwaNoodle** [lholman/OneBuild#37]
While debugging something I was working on I noticed that the files picked up in the New-NugetPackage were not the ones that should have been supplied by the Mock in the test but was the OneBuild nuspec file. This seems to be an issue with scoping on the Mocks and they're not behaving like expected from the documentation. 

The tests are passing but this appears to be luck of which mock in honoured.

**Comment by lholman** [comment]
Closed with PR #38
