### ISSUE TITLE
Errors in init.ps1 in PM console on opening a solution

### ISSUE THREAD

**Issue by nightroman** [lholman/OneBuild#47]
After installing OneBuild, on opening the solution in Visual Studio next time I see errors in the PM console:

    Copy-Item : Cannot find path 'C:\tmp\ClassLibrary1\packages\OneBuild.1.0.95\tools\temp' because it does not exist.
    At C:\tmp\ClassLibrary1\packages\OneBuild.1.0.95\tools\init.ps1:4 char:1
    ...
     
    Remove-Item : Cannot find path 'C:\tmp\ClassLibrary1\packages\OneBuild.1.0.95\tools\temp\' because it does not exist.
    At C:\tmp\ClassLibrary1\packages\OneBuild.1.0.95\tools\init.ps1:5 char:1
    ...

What I have done:

- VS 2013, new project/solution, type library.
- `PM> Install-Package OneBuild` - works fine, installed 4 packages
- Exit VS, open again, open the last solution. As a result the PM console shows the above errors.

Is it something wrong with my installation or *OneBuild.1.0.95\tools\init.ps1*?

**Comment by nightroman** [comment]
From the top of my head, should not it perhaps be *install.ps1*, not *init.ps1*? Then it all makes sense. On installation it copies files. Then on opening a project nothing should be done and the file *init.ps1* is not even needed.

**Comment by lholman** [comment]
@nightroman Thanks for finding this. I'll reproduce and get a fix out ASAP

**Comment by nightroman** [comment]
No problem! Note that it's a minor issue, it does not make any real harm.

**Comment by nightroman** [comment]
BTW, I would recommend to use the latest Invoke-Build 2.12.0. There are some improvements and fixes since 2.9.12. Also, the package now includes only core tools in order to keep it focused on main tasks. This especially makes sense for tools like *OneBuild*, *[PowerTasks](https://github.com/shaynevanasperen/PowerTasks)*, etc., they need just the Invoke-Build engine.

**Comment by nightroman** [comment]
Yet another reason to upgrade. OneBuild showed me another issue. The issue is caused by *TabExpansionProfile.Invoke-Build.ps1* (excluded now but exists in 2.9.12 which comes with OneBuild). I use TabExpansion completers from it and I have my own version of it in the path. Thus, when Visual Studio starts with a project with OneBuild and I hit TabExpansion in the Package Manages console the both files are found the path. This is not a fatal issue, errors are handled nice and quietly but they can be avoided if *TabExpansionProfile.Invoke-Build.ps1* simply excluded from the package.

**Comment by lholman** [comment]
@nightroman I've taken your last comment and will handle it as part of #52, picking up the original issue too.

**Comment by lholman** [comment]
"From the top of my head, should not it perhaps be install.ps1, not init.ps1? Then it all makes sense. On installation it copies files. Then on opening a project nothing should be done and the file init.ps1 is not even needed."

So, this got me thinking about my previous choice of `init.ps1`, which simply copies some files to the solution root directory, on package install, like so.

```
param($installPath, $toolsPath, $package)

#Forces the Batch and PS scripts for executing the build up to the root solution folder.
Copy-Item "$installPath\tools\temp\*.*" -destination "$installPath\..\..\" -recurse
Remove-Item "$installPath\tools\temp\" -recurse 
```

My decision to use `initi.ps1` was based on the following "Init.ps1 runs the first time a package is installed in a solution." Taken from https://docs.nuget.org/create/creating-and-publishing-a-package

Now, OneBuild is a solution level NuGet package, not a project level one, so `Install.ps1` didn't seem appropriate "Install.ps1 runs when a package is installed in a project.", again from the same nuget documentation.

What I don't really like from `init.ps1` is "The script also runs every time the solution is opened", but that is caveat-ed with "(Package Manager Console window has to be open at the same for the script to run)."

So, this is a bit of an edge case, but still, many people probably have the Package Manager COnsole window open by default. Maybe a simple Test-Path is all that's needed?

**Comment by lholman** [comment]
@nightroman something like this I think.

```
param($installPath, $toolsPath, $package)

#Forces the Batch and PS scripts for executing OneBuild up to the root solution folder.
if (Test-Path "$toolsPath\temp")
{
    Copy-Item "$toolsPath\temp\*.*" -destination "$installPath\..\..\" -recurse
    Remove-Item "$toolsPath\temp\" -recurse 
}
```

**Comment by nightroman** [comment]
I cannot tell what is the best solution in this scenario. I just noticed errors and reported them. If they are avoided then the issue is resolved.
