### ISSUE TITLE
Multiprocessor MSBuild switch without node recycling can lead to locked builds

### ISSUE THREAD

**Issue by AwaNoodle** [lholman/OneBuild#49]
I've encountered an issue where files brought in by a solution to build are being kept open by MSBuild processes (in my case it was the BCL files or the targets used for MS Deploy Publishing). This has the effect of stopping a build when TeamCity tries to clean the working folder and retry the build. 

I've experimented with turning off /m which works but obviously is a problem. I had more success with using /nr:false as the created build processes are not kept around to lock the files.

**Comment by lholman** [comment]
Fixed with PR #50
